### ISSUE TITLE
Tracking issue: CLI client

### ISSUE THREAD

**Issue by tisnik** [tisnik/smallsource#41]
# Suggestions

Create CLI client.

## Requirements

- [ ] written in Python, as the rest of this tool
- [ ] support for REPL
- [ ] automatic command completion
- [ ] support for data exports
- [ ] support for data imports
